export const categories: Record<string,string> = {
    "2bdFPJUvFo": "18XX",
    "85OKv8p5Ow": "4x",
    "FMKgeuNEII": "80s",
    "hBqZ3Ar4RJ": "Abstract",
    "GtuMb7ei27": "Accessory",
    "OE07lsfVqf": "Adult",
    "KUBCKBkGxV": "Adventure",
    "DjAhqEHOD0": "Aerial Warfare",
    "20iDvpbh7A": "Age of Reason",
    "tJxatX2ZbW": "Aliens",
    "nWDac9tQzt": "Alternate History",
    "dghLhwyxVb": "American History",
    "4mOtRRwSoj": "American West",
    "a8NM5cugJX": "Ancient",
    "MWoxgHrOJD": "Animals",
    "eFaACC6y2c": "Apocalyptic",
    "CBboNLI1Uj": "Arabian",
    "k0dglq5j6N": "Art",
    "Bq6M0TJyg7": "Asymmetric",
    "QB4sEpx1Uu": "Aviation",
    "wpItJuRDiz": "Banking",
    "pwt9HAzEa6": "Battle Royale",
    "PinhJrhnxU": "Bluffing",
    "wLpYxHBexW": "Book",
    "fW5vusE96B": "Campaign",
    "eX8uuNlQkQ": "Card Game",
    "HKaYVNIxAJ": "Children's Game",
    "36WFElclV3": "Christian",
    "3Y1dIDLCRw": "Christmas",
    "ODWOjWAJj3": "City Building",
    "w8XD66FUZ2": "Civil War",
    "329DxyFL9D": "Civilization",
    "bVMxJo31bS": "Cold war",
    "vXxLT0FDTZ": "Collectible Components",
    "bSzUpE5oOZ": "Colonial",
    "gscaL52VDG": "Combat",
    "G5kfqnPBP6": "Comic Book / Strip",
    "pacCjl7His": "Competitive",
    "ge8pIhEUGE": "Cooperative",
    "7DfHn28Pcf": "Crime",
    "nfQONtMbDU": "Cube Rail",
    "Ef4oYLHNhI": "Cyberpunk",
    "bCBXJy9qDw": "Deduction",
    "fh4V5SOLFj": "Deluxe Edition",
    "bKrxqD9mYc": "Dexterity",
    "mavSOM8vjH": "Dice",
    "42pmul4oHH": "Dinosaurs",
    "zoOGfQ9rK3": "Dogs",
    "JMM0TG2MSe": "Drawing",
    "We3MM46qBr": "Drinking",
    "g2Hwv8t0Y5": "Dungeon Crawl",
    "N0TkEGfEsF": "Economic",
    "B3NRLMK4xD": "Educational",
    "crxgUzJSEz": "Electronic",
    "gsekjrPJz0": "Environmental",
    "pflvcNyHPe": "Escape Room",
    "u5ZiYctU6T": "Espionage",
    "v4SfYtS2Lr": "Expansion",
    "yq6hVlbM2R": "Exploration",
    "7rV11PKqME": "Family Game",
    "ctumBZyj5l": "Fan Made",
    "ZTneo8TaIO": "Fantasy",
    "Wr8uXcoR9p": "Farming",
    "upXZ8vNfNO": "Fighting",
    "ELg06sncRX": "Finance",
    "YrDuNj8lvr": "Food",
    "JvIs75sWte": "Game System",
    "cQnyClrGPU": "Gamefound",
    "Eyuf8PzjDo": "Gulf War",
    "KzEQIwIub7": "Historic",
    "cAIkk5aLdQ": "Horror",
    "TYnxiuiI3X": "Humor",
    "zqFmdU4Fp2": "Industry/Manufacturing",
    "rrvd68LjOR": "Kickstarter",
    "3souLOXUqI": "Korean War",
    "AGKGd3txp9": "Law",
    "XeYUw9159M": "Legacy",
    "HZ7kUiqEbs": "Letters",
    "GCwXmvBCvA": "Mad Scientist",
    "pIMmuVYnQp": "Mafia",
    "POlqwScVxD": "Math",
    "ZhlfIPxYsw": "Mature / Adult",
    "ruQAhyLfum": "Maze",
    "AeWXMxbm91": "Medical",
    "QAYkTHK1Dd": "Medieval",
    "AujCle9cUq": "Memory",
    "Cc10AY9UX5": "Mental Health",
    "FC6ElKI9tk": "Miniatures",
    "L6NUwNdblq": "Modern Warfare",
    "Sod2YBWMKi": "Movies / TV / Radio theme",
    "1e709CZ42V": "Murder",
    "Kk70K0524Z": "Murder/Mystery",
    "herNFAxMdz": "Music",
    "BBZb2d0ePt": "Mystery",
    "MHkqIVxwtx": "Mythology",
    "IpcJzp0TVC": "Napoleonic",
    "o5dH2ssbuu": "Nature",
    "vqZ5XzGWQD": "Nautical",
    "jZEDOpx07e": "Negotiation",
    "rtslXnT90O": "Ninjas",
    "dO9HVl2TW7": "Novel-based",
    "9r6mtYVCAZ": "Number",
    "i9YgN1u0Al": "Objectives",
    "TCYEfWLB8c": "One vs Many",
    "SE2CndXU4V": "Paranormal",
    "X8J7RM6dxX": "Party Game",
    "B70QTH9k5o": "Path building",
    "UL3b9M86gA": "Pike and Shot",
    "9EIayX6n5a": "Pirates",
    "vRbkg1W0AB": "Plants/Gardening",
    "3EjfGzCuWE": "Point Salad",
    "TKQncFVX74": "Political",
    "8Z7nWG2kOw": "Post-Apocalyptic",
    "5APB1MWk6X": "Post-Napoleonic",
    "YyszHun1HP": "Prehistoric",
    "ov6sEmlkiC": "Print & Play",
    "dAyk5NtNTV": "Prison Escape",
    "AlrfWcR5aT": "Promo",
    "WVMOS3s2pb": "Puzzle",
    "2Gu62aKdma": "RPG",
    "tQGLgwdbYH": "Racing",
    "PzWI2uaif0": "Real-time",
    "DRqeVkXWqX": "Religious",
    "nuHYRFmMjU": "Renaissance",
    "zyj9ZK3mHB": "Resource Management",
    "oojGpMQQ2l": "Robots",
    "KSBdPfxs6F": "Roman Empire",
    "E5rYwP0Ybr": "Romance",
    "SzUZdSjCN2": "Route Building",
    "UH3xvKjaCQ": "Safari",
    "2m6sfYeeGI": "Sandbox",
    "3B3QpKvXD3": "Sci-Fi",
    "UjUO40mmeL": "Screen Printed Meeples",
    "WCMkyAqVlf": "Semi-Cooperative",
    "VzyslQJGrG": "Solo / Solitaire",
    "0MdRqhkNpw": "Space Exploration",
    "Hc6vcim5DS": "Spies/Secret Agents",
    "hShsL2DktG": "Sports",
    "4hZlqoitAY": "Steampunk",
    "jGXefW0E2i": "Storytelling",
    "alkjFhA58S": "Strategic-Level",
    "loGUMKV9K9": "Tactical-Level",
    "knFtS8LntM": "Technology",
    "buDTYyPw4D": "Territory Building",
    "XN9Byxf3MK": "Theme Park",
    "BHxvD7ZjfA": "Tile Placement",
    "L18sB21wyi": "Tile drafting",
    "2KVQJ2k60k": "Time Travel",
    "JwHcKqxh33": "Trains",
    "CWYOF9xu7O": "Transportation",
    "TR4CiP8Huj": "Travel",
    "YGHGDjahKY": "Trivia",
    "a2eMKxxlVW": "Two player Only Game",
    "oHSL7C6i9y": "Undersea",
    "djokexoK0U": "Video Game Theme",
    "jS8aA9kDFW": "Vietnam War",
    "muDQil3Mkb": "Viking",
    "jX8asGGR6o": "Wargame",
    "uJgSEPT6zE": "Werewolves",
    "mw3nPNWqs0": "Western",
    "rHvAx4hH2f": "Word Game",
    "wTLJSVEbm6": "World War I",
    "fl3TogdUzX": "World War II",
    "OlkGBmu4Va": "World War III",
    "djZWzjCZhM": "Writing / Dry Erase",
    "30B899LSDs": "Zodiac",
    "FmGV9rVu1c": "Zombies",
    "B1N2QOByCl": "Zone Control"
}
