name = "my-partyserver-app"
main = "src/server/index.ts"
compatibility_date = "2024-09-02"

[vars]
GOOGLE_API_URL = "https://www.googleapis.com"

[[durable_objects.bindings]]
name = "MyServer"
class_name = "MyServer"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["MyServer"]
