name = "margins-partyserver"
main = "src/server/index.ts"
compatibility_date = "2024-09-02"

[vars]
GOOGLE_API_URL = "https://www.googleapis.com"

[[durable_objects.bindings]]
name = "MarginsServer"
class_name = "MarginsServer"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["MarginsServer"]
